name: Contributors Page

on:
  pull_request:
    types: [ closed ]

jobs:
  contributors:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Generate contributors page
      run: bin/build_contributors
    - name: Upload Contributors Page to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: 'wiki'
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN   }}

